"""Public application facade and typed Phase-1 contracts."""

from .composition import create_application
from .facade import ApplicationFacade
from .models import (
    ApplicationError,
    ApplyReview,
    BackupSnapshot,
    BaselineListSnapshot,
    BaselineShowSnapshot,
    BaselineUseSnapshot,
    CapacitySnapshot,
    CompatibilityObservation,
    DebugExportSnapshot,
    ErrorCode,
    InspectSnapshot,
    OperationResult,
    PersistentOperationKind,
    PlanSnapshot,
    PreparedOperation,
    PrivacyClass,
    ProbeDetails,
    ProbeSnapshot,
    ProfileSwitchResult,
    PublicReportSnapshot,
    ReadonlySmokeSnapshot,
    ReportCheckResult,
    SetupSnapshot,
    StatusSnapshot,
    ValidationDetails,
    ValidationSnapshot,
    WriteEligibility,
)

__all__ = [
    "ApplicationError",
    "ApplicationFacade",
    "ApplyReview",
    "BackupSnapshot",
    "BaselineListSnapshot",
    "BaselineShowSnapshot",
    "BaselineUseSnapshot",
    "CapacitySnapshot",
    "CompatibilityObservation",
    "DebugExportSnapshot",
    "ErrorCode",
    "InspectSnapshot",
    "OperationResult",
    "PersistentOperationKind",
    "PlanSnapshot",
    "PreparedOperation",
    "PrivacyClass",
    "ProbeDetails",
    "ProbeSnapshot",
    "ProfileSwitchResult",
    "PublicReportSnapshot",
    "ReadonlySmokeSnapshot",
    "ReportCheckResult",
    "SetupSnapshot",
    "StatusSnapshot",
    "ValidationDetails",
    "ValidationSnapshot",
    "WriteEligibility",
    "create_application",
]
